// Code generated by internal/gen. DO NOT EDIT.

package functional

// Tuple2 groups two values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple2[A, B any] struct {
	First  A
	Second B
}

// NewTuple2 builds a Tuple2 from its two values.
func NewTuple2[A, B any](first A, second B) Tuple2[A, B] {
	return Tuple2[A, B]{First: first, Second: second}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple2[A, B]) Unpack() (A, B) {
	return t.First, t.Second
}

// Tuple3 groups three values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple3[A, B, C any] struct {
	First  A
	Second B
	Third  C
}

// NewTuple3 builds a Tuple3 from its three values.
func NewTuple3[A, B, C any](first A, second B, third C) Tuple3[A, B, C] {
	return Tuple3[A, B, C]{First: first, Second: second, Third: third}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple3[A, B, C]) Unpack() (A, B, C) {
	return t.First, t.Second, t.Third
}

// Tuple4 groups four values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple4[A, B, C, D any] struct {
	First  A
	Second B
	Third  C
	Fourth D
}

// NewTuple4 builds a Tuple4 from its four values.
func NewTuple4[A, B, C, D any](first A, second B, third C, fourth D) Tuple4[A, B, C, D] {
	return Tuple4[A, B, C, D]{First: first, Second: second, Third: third, Fourth: fourth}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple4[A, B, C, D]) Unpack() (A, B, C, D) {
	return t.First, t.Second, t.Third, t.Fourth
}

// Tuple5 groups five values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple5[A, B, C, D, E any] struct {
	First  A
	Second B
	Third  C
	Fourth D
	Fifth  E
}

// NewTuple5 builds a Tuple5 from its five values.
func NewTuple5[A, B, C, D, E any](first A, second B, third C, fourth D, fifth E) Tuple5[A, B, C, D, E] {
	return Tuple5[A, B, C, D, E]{First: first, Second: second, Third: third, Fourth: fourth, Fifth: fifth}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple5[A, B, C, D, E]) Unpack() (A, B, C, D, E) {
	return t.First, t.Second, t.Third, t.Fourth, t.Fifth
}

// Tuple6 groups six values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple6[A, B, C, D, E, F any] struct {
	First  A
	Second B
	Third  C
	Fourth D
	Fifth  E
	Sixth  F
}

// NewTuple6 builds a Tuple6 from its six values.
func NewTuple6[A, B, C, D, E, F any](first A, second B, third C, fourth D, fifth E, sixth F) Tuple6[A, B, C, D, E, F] {
	return Tuple6[A, B, C, D, E, F]{First: first, Second: second, Third: third, Fourth: fourth, Fifth: fifth, Sixth: sixth}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple6[A, B, C, D, E, F]) Unpack() (A, B, C, D, E, F) {
	return t.First, t.Second, t.Third, t.Fourth, t.Fifth, t.Sixth
}

// Tuple7 groups seven values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple7[A, B, C, D, E, F, G any] struct {
	First   A
	Second  B
	Third   C
	Fourth  D
	Fifth   E
	Sixth   F
	Seventh G
}

// NewTuple7 builds a Tuple7 from its seven values.
func NewTuple7[A, B, C, D, E, F, G any](first A, second B, third C, fourth D, fifth E, sixth F, seventh G) Tuple7[A, B, C, D, E, F, G] {
	return Tuple7[A, B, C, D, E, F, G]{First: first, Second: second, Third: third, Fourth: fourth, Fifth: fifth, Sixth: sixth, Seventh: seventh}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple7[A, B, C, D, E, F, G]) Unpack() (A, B, C, D, E, F, G) {
	return t.First, t.Second, t.Third, t.Fourth, t.Fifth, t.Sixth, t.Seventh
}

// Tuple8 groups eight values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple8[A, B, C, D, E, F, G, H any] struct {
	First   A
	Second  B
	Third   C
	Fourth  D
	Fifth   E
	Sixth   F
	Seventh G
	Eighth  H
}

// NewTuple8 builds a Tuple8 from its eight values.
func NewTuple8[A, B, C, D, E, F, G, H any](first A, second B, third C, fourth D, fifth E, sixth F, seventh G, eighth H) Tuple8[A, B, C, D, E, F, G, H] {
	return Tuple8[A, B, C, D, E, F, G, H]{First: first, Second: second, Third: third, Fourth: fourth, Fifth: fifth, Sixth: sixth, Seventh: seventh, Eighth: eighth}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple8[A, B, C, D, E, F, G, H]) Unpack() (A, B, C, D, E, F, G, H) {
	return t.First, t.Second, t.Third, t.Fourth, t.Fifth, t.Sixth, t.Seventh, t.Eighth
}

// Tuple9 groups nine values of possibly different types. It carries no
// absence or failure state of its own — it exists so one step in a chain can
// hand more than one value to the next without an ad hoc struct.
type Tuple9[A, B, C, D, E, F, G, H, I any] struct {
	First   A
	Second  B
	Third   C
	Fourth  D
	Fifth   E
	Sixth   F
	Seventh G
	Eighth  H
	Ninth   I
}

// NewTuple9 builds a Tuple9 from its nine values.
func NewTuple9[A, B, C, D, E, F, G, H, I any](first A, second B, third C, fourth D, fifth E, sixth F, seventh G, eighth H, ninth I) Tuple9[A, B, C, D, E, F, G, H, I] {
	return Tuple9[A, B, C, D, E, F, G, H, I]{First: first, Second: second, Third: third, Fourth: fourth, Fifth: fifth, Sixth: sixth, Seventh: seventh, Eighth: eighth, Ninth: ninth}
}

// Unpack returns the values as separate results, so a caller can bind them all
// in one statement instead of reading fields one at a time.
func (t Tuple9[A, B, C, D, E, F, G, H, I]) Unpack() (A, B, C, D, E, F, G, H, I) {
	return t.First, t.Second, t.Third, t.Fourth, t.Fifth, t.Sixth, t.Seventh, t.Eighth, t.Ninth
}
