// Code generated by internal/gen. DO NOT EDIT.

package functional

// ZipValidation2 combines two independent Validations into one
// Validation carrying a Tuple2 of their values. This is where Validation
// parts ways with Result: ZipResult2 propagates only the leftmost error,
// while ZipValidation2 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation2[A, B any](a Validation[A], b Validation[B]) Validation[Tuple2[A, B]] {
	if errs := collectErrs(a.errs, b.errs); len(errs) > 0 {
		return Validation[Tuple2[A, B]]{errs: errs}
	}
	return Valid(NewTuple2(a.v, b.v))
}

// ZipValidation3 combines three independent Validations into one
// Validation carrying a Tuple3 of their values. This is where Validation
// parts ways with Result: ZipResult3 propagates only the leftmost error,
// while ZipValidation3 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation3[A, B, C any](a Validation[A], b Validation[B], c Validation[C]) Validation[Tuple3[A, B, C]] {
	if errs := collectErrs(a.errs, b.errs, c.errs); len(errs) > 0 {
		return Validation[Tuple3[A, B, C]]{errs: errs}
	}
	return Valid(NewTuple3(a.v, b.v, c.v))
}

// ZipValidation4 combines four independent Validations into one
// Validation carrying a Tuple4 of their values. This is where Validation
// parts ways with Result: ZipResult4 propagates only the leftmost error,
// while ZipValidation4 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation4[A, B, C, D any](a Validation[A], b Validation[B], c Validation[C], d Validation[D]) Validation[Tuple4[A, B, C, D]] {
	if errs := collectErrs(a.errs, b.errs, c.errs, d.errs); len(errs) > 0 {
		return Validation[Tuple4[A, B, C, D]]{errs: errs}
	}
	return Valid(NewTuple4(a.v, b.v, c.v, d.v))
}

// ZipValidation5 combines five independent Validations into one
// Validation carrying a Tuple5 of their values. This is where Validation
// parts ways with Result: ZipResult5 propagates only the leftmost error,
// while ZipValidation5 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation5[A, B, C, D, E any](a Validation[A], b Validation[B], c Validation[C], d Validation[D], e Validation[E]) Validation[Tuple5[A, B, C, D, E]] {
	if errs := collectErrs(a.errs, b.errs, c.errs, d.errs, e.errs); len(errs) > 0 {
		return Validation[Tuple5[A, B, C, D, E]]{errs: errs}
	}
	return Valid(NewTuple5(a.v, b.v, c.v, d.v, e.v))
}

// ZipValidation6 combines six independent Validations into one
// Validation carrying a Tuple6 of their values. This is where Validation
// parts ways with Result: ZipResult6 propagates only the leftmost error,
// while ZipValidation6 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation6[A, B, C, D, E, F any](a Validation[A], b Validation[B], c Validation[C], d Validation[D], e Validation[E], f Validation[F]) Validation[Tuple6[A, B, C, D, E, F]] {
	if errs := collectErrs(a.errs, b.errs, c.errs, d.errs, e.errs, f.errs); len(errs) > 0 {
		return Validation[Tuple6[A, B, C, D, E, F]]{errs: errs}
	}
	return Valid(NewTuple6(a.v, b.v, c.v, d.v, e.v, f.v))
}

// ZipValidation7 combines seven independent Validations into one
// Validation carrying a Tuple7 of their values. This is where Validation
// parts ways with Result: ZipResult7 propagates only the leftmost error,
// while ZipValidation7 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation7[A, B, C, D, E, F, G any](a Validation[A], b Validation[B], c Validation[C], d Validation[D], e Validation[E], f Validation[F], g Validation[G]) Validation[Tuple7[A, B, C, D, E, F, G]] {
	if errs := collectErrs(a.errs, b.errs, c.errs, d.errs, e.errs, f.errs, g.errs); len(errs) > 0 {
		return Validation[Tuple7[A, B, C, D, E, F, G]]{errs: errs}
	}
	return Valid(NewTuple7(a.v, b.v, c.v, d.v, e.v, f.v, g.v))
}

// ZipValidation8 combines eight independent Validations into one
// Validation carrying a Tuple8 of their values. This is where Validation
// parts ways with Result: ZipResult8 propagates only the leftmost error,
// while ZipValidation8 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation8[A, B, C, D, E, F, G, H any](a Validation[A], b Validation[B], c Validation[C], d Validation[D], e Validation[E], f Validation[F], g Validation[G], h Validation[H]) Validation[Tuple8[A, B, C, D, E, F, G, H]] {
	if errs := collectErrs(a.errs, b.errs, c.errs, d.errs, e.errs, f.errs, g.errs, h.errs); len(errs) > 0 {
		return Validation[Tuple8[A, B, C, D, E, F, G, H]]{errs: errs}
	}
	return Valid(NewTuple8(a.v, b.v, c.v, d.v, e.v, f.v, g.v, h.v))
}

// ZipValidation9 combines nine independent Validations into one
// Validation carrying a Tuple9 of their values. This is where Validation
// parts ways with Result: ZipResult9 propagates only the leftmost error,
// while ZipValidation9 collects the errors from every invalid input,
// concatenated left to right in argument order — so a caller can render
// field errors in the order the fields appear on the form.
//
// The result is valid only when every input is valid.
func ZipValidation9[A, B, C, D, E, F, G, H, I any](a Validation[A], b Validation[B], c Validation[C], d Validation[D], e Validation[E], f Validation[F], g Validation[G], h Validation[H], i Validation[I]) Validation[Tuple9[A, B, C, D, E, F, G, H, I]] {
	if errs := collectErrs(a.errs, b.errs, c.errs, d.errs, e.errs, f.errs, g.errs, h.errs, i.errs); len(errs) > 0 {
		return Validation[Tuple9[A, B, C, D, E, F, G, H, I]]{errs: errs}
	}
	return Valid(NewTuple9(a.v, b.v, c.v, d.v, e.v, f.v, g.v, h.v, i.v))
}
