// Code generated by internal/gen. DO NOT EDIT.

package functional

// ZipOption2 combines two independent Options into one Option carrying
// a Tuple2 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption2[A, B any](a Option[A], b Option[B]) Option[Tuple2[A, B]] {
	if err := firstErr(a.err, b.err); err != nil {
		return Failed[Tuple2[A, B]](err)
	}
	if !a.IsPresent() || !b.IsPresent() {
		return None[Tuple2[A, B]]()
	}
	return Some(NewTuple2(a.v, b.v))
}

// ZipResult2 combines two independent Results into one Result carrying
// a Tuple2 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult2[A, B any](a Result[A], b Result[B]) Result[Tuple2[A, B]] {
	if err := firstErr(a.err, b.err); err != nil {
		return Failure[Tuple2[A, B]](err)
	}
	return Ok(NewTuple2(a.v, b.v))
}

// ZipOption3 combines three independent Options into one Option carrying
// a Tuple3 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption3[A, B, C any](a Option[A], b Option[B], c Option[C]) Option[Tuple3[A, B, C]] {
	if err := firstErr(a.err, b.err, c.err); err != nil {
		return Failed[Tuple3[A, B, C]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() {
		return None[Tuple3[A, B, C]]()
	}
	return Some(NewTuple3(a.v, b.v, c.v))
}

// ZipResult3 combines three independent Results into one Result carrying
// a Tuple3 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult3[A, B, C any](a Result[A], b Result[B], c Result[C]) Result[Tuple3[A, B, C]] {
	if err := firstErr(a.err, b.err, c.err); err != nil {
		return Failure[Tuple3[A, B, C]](err)
	}
	return Ok(NewTuple3(a.v, b.v, c.v))
}

// ZipOption4 combines four independent Options into one Option carrying
// a Tuple4 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption4[A, B, C, D any](a Option[A], b Option[B], c Option[C], d Option[D]) Option[Tuple4[A, B, C, D]] {
	if err := firstErr(a.err, b.err, c.err, d.err); err != nil {
		return Failed[Tuple4[A, B, C, D]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() || !d.IsPresent() {
		return None[Tuple4[A, B, C, D]]()
	}
	return Some(NewTuple4(a.v, b.v, c.v, d.v))
}

// ZipResult4 combines four independent Results into one Result carrying
// a Tuple4 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult4[A, B, C, D any](a Result[A], b Result[B], c Result[C], d Result[D]) Result[Tuple4[A, B, C, D]] {
	if err := firstErr(a.err, b.err, c.err, d.err); err != nil {
		return Failure[Tuple4[A, B, C, D]](err)
	}
	return Ok(NewTuple4(a.v, b.v, c.v, d.v))
}

// ZipOption5 combines five independent Options into one Option carrying
// a Tuple5 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption5[A, B, C, D, E any](a Option[A], b Option[B], c Option[C], d Option[D], e Option[E]) Option[Tuple5[A, B, C, D, E]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err); err != nil {
		return Failed[Tuple5[A, B, C, D, E]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() || !d.IsPresent() || !e.IsPresent() {
		return None[Tuple5[A, B, C, D, E]]()
	}
	return Some(NewTuple5(a.v, b.v, c.v, d.v, e.v))
}

// ZipResult5 combines five independent Results into one Result carrying
// a Tuple5 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult5[A, B, C, D, E any](a Result[A], b Result[B], c Result[C], d Result[D], e Result[E]) Result[Tuple5[A, B, C, D, E]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err); err != nil {
		return Failure[Tuple5[A, B, C, D, E]](err)
	}
	return Ok(NewTuple5(a.v, b.v, c.v, d.v, e.v))
}

// ZipOption6 combines six independent Options into one Option carrying
// a Tuple6 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption6[A, B, C, D, E, F any](a Option[A], b Option[B], c Option[C], d Option[D], e Option[E], f Option[F]) Option[Tuple6[A, B, C, D, E, F]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err); err != nil {
		return Failed[Tuple6[A, B, C, D, E, F]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() || !d.IsPresent() || !e.IsPresent() || !f.IsPresent() {
		return None[Tuple6[A, B, C, D, E, F]]()
	}
	return Some(NewTuple6(a.v, b.v, c.v, d.v, e.v, f.v))
}

// ZipResult6 combines six independent Results into one Result carrying
// a Tuple6 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult6[A, B, C, D, E, F any](a Result[A], b Result[B], c Result[C], d Result[D], e Result[E], f Result[F]) Result[Tuple6[A, B, C, D, E, F]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err); err != nil {
		return Failure[Tuple6[A, B, C, D, E, F]](err)
	}
	return Ok(NewTuple6(a.v, b.v, c.v, d.v, e.v, f.v))
}

// ZipOption7 combines seven independent Options into one Option carrying
// a Tuple7 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption7[A, B, C, D, E, F, G any](a Option[A], b Option[B], c Option[C], d Option[D], e Option[E], f Option[F], g Option[G]) Option[Tuple7[A, B, C, D, E, F, G]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err, g.err); err != nil {
		return Failed[Tuple7[A, B, C, D, E, F, G]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() || !d.IsPresent() || !e.IsPresent() || !f.IsPresent() || !g.IsPresent() {
		return None[Tuple7[A, B, C, D, E, F, G]]()
	}
	return Some(NewTuple7(a.v, b.v, c.v, d.v, e.v, f.v, g.v))
}

// ZipResult7 combines seven independent Results into one Result carrying
// a Tuple7 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult7[A, B, C, D, E, F, G any](a Result[A], b Result[B], c Result[C], d Result[D], e Result[E], f Result[F], g Result[G]) Result[Tuple7[A, B, C, D, E, F, G]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err, g.err); err != nil {
		return Failure[Tuple7[A, B, C, D, E, F, G]](err)
	}
	return Ok(NewTuple7(a.v, b.v, c.v, d.v, e.v, f.v, g.v))
}

// ZipOption8 combines eight independent Options into one Option carrying
// a Tuple8 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption8[A, B, C, D, E, F, G, H any](a Option[A], b Option[B], c Option[C], d Option[D], e Option[E], f Option[F], g Option[G], h Option[H]) Option[Tuple8[A, B, C, D, E, F, G, H]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err, g.err, h.err); err != nil {
		return Failed[Tuple8[A, B, C, D, E, F, G, H]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() || !d.IsPresent() || !e.IsPresent() || !f.IsPresent() || !g.IsPresent() || !h.IsPresent() {
		return None[Tuple8[A, B, C, D, E, F, G, H]]()
	}
	return Some(NewTuple8(a.v, b.v, c.v, d.v, e.v, f.v, g.v, h.v))
}

// ZipResult8 combines eight independent Results into one Result carrying
// a Tuple8 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult8[A, B, C, D, E, F, G, H any](a Result[A], b Result[B], c Result[C], d Result[D], e Result[E], f Result[F], g Result[G], h Result[H]) Result[Tuple8[A, B, C, D, E, F, G, H]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err, g.err, h.err); err != nil {
		return Failure[Tuple8[A, B, C, D, E, F, G, H]](err)
	}
	return Ok(NewTuple8(a.v, b.v, c.v, d.v, e.v, f.v, g.v, h.v))
}

// ZipOption9 combines nine independent Options into one Option carrying
// a Tuple9 of their values. Use it when the lookups do not depend on each
// other; when a later lookup is keyed by an earlier one's value, chain with
// FlatMap instead.
//
// The result is present only when every input is present. A failure outranks
// absence — the leftmost error is propagated — so a caller checking Err first
// never mistakes a real failure for a missing value.
func ZipOption9[A, B, C, D, E, F, G, H, I any](a Option[A], b Option[B], c Option[C], d Option[D], e Option[E], f Option[F], g Option[G], h Option[H], i Option[I]) Option[Tuple9[A, B, C, D, E, F, G, H, I]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err, g.err, h.err, i.err); err != nil {
		return Failed[Tuple9[A, B, C, D, E, F, G, H, I]](err)
	}
	if !a.IsPresent() || !b.IsPresent() || !c.IsPresent() || !d.IsPresent() || !e.IsPresent() || !f.IsPresent() || !g.IsPresent() || !h.IsPresent() || !i.IsPresent() {
		return None[Tuple9[A, B, C, D, E, F, G, H, I]]()
	}
	return Some(NewTuple9(a.v, b.v, c.v, d.v, e.v, f.v, g.v, h.v, i.v))
}

// ZipResult9 combines nine independent Results into one Result carrying
// a Tuple9 of their values. It succeeds only when every input succeeded;
// otherwise the leftmost error is propagated.
func ZipResult9[A, B, C, D, E, F, G, H, I any](a Result[A], b Result[B], c Result[C], d Result[D], e Result[E], f Result[F], g Result[G], h Result[H], i Result[I]) Result[Tuple9[A, B, C, D, E, F, G, H, I]] {
	if err := firstErr(a.err, b.err, c.err, d.err, e.err, f.err, g.err, h.err, i.err); err != nil {
		return Failure[Tuple9[A, B, C, D, E, F, G, H, I]](err)
	}
	return Ok(NewTuple9(a.v, b.v, c.v, d.v, e.v, f.v, g.v, h.v, i.v))
}
